title: "Koda Ermini — CS-499 ePortfolio"
description: "SNHU Computer Science Capstone (CS-499) — Enhanced artifacts in Software Engineering & Design, Algorithms & Data Structures, and Databases."
theme: jekyll-theme-cayman
show_downloads: false
markdown: kramdown
